using DNTU.SkillBridge.Domain.Catalog;
using DNTU.SkillBridge.Domain.Common;

namespace DNTU.SkillBridge.Domain.Projects;

/// <summary>
/// Lifecycle state of a project. Member names intentionally match the uppercase
/// wire values (e.g. PENDING_APPROVAL). Draft-only editing is Task 12; the
/// submit/approve transitions arrive with Task 13.
/// </summary>
public enum ProjectStatus
{
    DRAFT = 1,
    PENDING_APPROVAL = 2,
    CHANGES_REQUESTED = 3,
    APPROVED = 4,
    RECRUITING = 5,
    IN_PROGRESS = 6,
    COMPLETED = 7,
    CANCELLED = 8,
    REJECTED = 9,
    SUSPENDED = 10
}

public enum RequirementLevel
{
    NICE_TO_HAVE = 1,
    IMPORTANT = 2,
    MUST_HAVE = 3
}

public sealed class Project : AuditableEntity
{
    public Guid CompanyId { get; private set; }
    public DNTU.SkillBridge.Domain.Companies.Company Company { get; private set; } = null!;

    /// <summary>Human-friendly reference code (e.g. PRJ-1A2B3C4D); generated by the service.</summary>
    public string Code { get; private set; } = string.Empty;
    public string Title { get; private set; } = string.Empty;
    public string NormalizedTitle { get; private set; } = string.Empty;
    public string Slug { get; private set; } = string.Empty;
    public string? Summary { get; private set; }
    public string? ProblemStatement { get; private set; }
    public string? BusinessRequirements { get; private set; }
    public string? TechnicalConstraints { get; private set; }
    public Guid? IndustryId { get; private set; }
    public ProjectDifficulty Difficulty { get; private set; }
    public ProjectWorkType WorkType { get; private set; }
    public int DurationWeeks { get; private set; }
    public DateTimeOffset? ApplicationDeadline { get; private set; }
    public int ExpectedStudentCount { get; private set; }
    public int MinTeamSize { get; private set; }
    public int MaxTeamSize { get; private set; }
    public long? AllowanceAmount { get; private set; }
    public string? AllowanceCurrency { get; private set; }
    public ProjectStatus Status { get; private set; } = ProjectStatus.DRAFT;
    public bool IsActive { get; private set; } = true;

    /// <summary>Set when the company first submits the draft for admin review (Task 13 workflow).</summary>
    public DateTimeOffset? SubmittedAt { get; private set; }
    public Guid? SubmittedByUserId { get; private set; }
    public DateTimeOffset? ApprovedAt { get; private set; }
    public Guid? ApprovedByUserId { get; private set; }

    /// <summary>Publication is driven purely by status (IsPubliclyVisible); this records when approval happened.</summary>
    public DateTimeOffset? PublishedAt { get; private set; }

    public ICollection<ProjectSkill> Skills { get; } = [];
    public ICollection<ProjectDeliverable> Deliverables { get; } = [];

    private Project() { }

    public Project(
        Guid companyId,
        string code,
        string title,
        ProjectDifficulty difficulty,
        ProjectWorkType workType,
        int durationWeeks,
        int expectedStudentCount,
        int minTeamSize,
        int maxTeamSize,
        string? summary,
        string? problemStatement,
        string? businessRequirements,
        string? technicalConstraints,
        Guid? industryId,
        DateTimeOffset? applicationDeadline,
        long? allowanceAmount,
        string? allowanceCurrency)
    {
        CompanyId = companyId;
        Code = code.Trim().ToUpperInvariant();
        Title = title.Trim();
        NormalizedTitle = Title.ToUpperInvariant();
        Slug = SlugBuilder.Create(Title);
        Difficulty = difficulty;
        WorkType = workType;
        DurationWeeks = durationWeeks;
        ExpectedStudentCount = expectedStudentCount;
        MinTeamSize = minTeamSize;
        MaxTeamSize = maxTeamSize;
        Summary = NormalizeText(summary);
        ProblemStatement = NormalizeText(problemStatement);
        BusinessRequirements = NormalizeText(businessRequirements);
        TechnicalConstraints = NormalizeText(technicalConstraints);
        IndustryId = industryId;
        ApplicationDeadline = applicationDeadline;
        AllowanceAmount = allowanceAmount;
        AllowanceCurrency = string.IsNullOrWhiteSpace(allowanceCurrency) ? null : allowanceCurrency.Trim().ToUpperInvariant();
        Status = ProjectStatus.DRAFT;
        IsActive = true;
    }

    /// <summary>Called once at creation to guarantee slug uniqueness.</summary>
    public void AssignSlug(string slug) => Slug = slug;

    /// <summary>Called once at creation to guarantee code uniqueness.</summary>
    public void AssignCode(string code) => Code = code.Trim().ToUpperInvariant();

    /// <summary>Mutates the draft content; anything other than a draft is immutable from the company side.</summary>
    public void UpdateDraft(
        string title,
        string? summary,
        string? problemStatement,
        string? businessRequirements,
        string? technicalConstraints,
        Guid? industryId,
        ProjectDifficulty difficulty,
        ProjectWorkType workType,
        int durationWeeks,
        DateTimeOffset? applicationDeadline,
        int expectedStudentCount,
        int minTeamSize,
        int maxTeamSize,
        long? allowanceAmount,
        string? allowanceCurrency)
    {
        if (Status != ProjectStatus.DRAFT)
        {
            throw new InvalidOperationException("Only projects in DRAFT status can be modified.");
        }

        Title = title.Trim();
        NormalizedTitle = Title.ToUpperInvariant();
        Slug = SlugBuilder.Create(Title);
        Summary = NormalizeText(summary);
        ProblemStatement = NormalizeText(problemStatement);
        BusinessRequirements = NormalizeText(businessRequirements);
        TechnicalConstraints = NormalizeText(technicalConstraints);
        IndustryId = industryId;
        Difficulty = difficulty;
        WorkType = workType;
        DurationWeeks = durationWeeks;
        ApplicationDeadline = applicationDeadline;
        ExpectedStudentCount = expectedStudentCount;
        MinTeamSize = minTeamSize;
        MaxTeamSize = maxTeamSize;
        AllowanceAmount = allowanceAmount;
        AllowanceCurrency = string.IsNullOrWhiteSpace(allowanceCurrency) ? null : allowanceCurrency.Trim().ToUpperInvariant();
    }

    /// <summary>Replaces the whole skill-requirement set; only drafts can be edited.</summary>
    public void ReplaceSkills(IEnumerable<(Guid SkillId, RequirementLevel Level, bool IsRequired)> skills)
    {
        if (Status != ProjectStatus.DRAFT)
        {
            throw new InvalidOperationException("Only projects in DRAFT status can be modified.");
        }

        Skills.Clear();
        foreach (var (skillId, level, isRequired) in skills)
        {
            Skills.Add(new ProjectSkill(Id, skillId, level, isRequired));
        }
    }

    /// <summary>Replaces the whole deliverable set; only drafts can be edited.</summary>
    public void SetDeliverables(IEnumerable<(string Name, string? Description, int SortOrder)> deliverables)
    {
        if (Status != ProjectStatus.DRAFT)
        {
            throw new InvalidOperationException("Only projects in DRAFT status can be modified.");
        }

        Deliverables.Clear();
        foreach (var (name, description, sortOrder) in deliverables)
        {
            Deliverables.Add(new ProjectDeliverable(Id, name, description, sortOrder));
        }
    }

    /// <summary>Soft delete; historical project data is preserved after submission (Task 13+).</summary>
    public void Deactivate()
    {
        if (Status != ProjectStatus.DRAFT)
        {
            throw new InvalidOperationException("Only projects in DRAFT status can be deleted.");
        }

        IsActive = false;
    }

    /// <summary>Company submits the draft for admin review; allowed from DRAFT or CHANGES_REQUESTED only.</summary>
    public void SubmitForApproval(Guid userId, DateTimeOffset now)
    {
        if (Status is not (ProjectStatus.DRAFT or ProjectStatus.CHANGES_REQUESTED))
        {
            throw new InvalidOperationException("Only DRAFT or CHANGES_REQUESTED projects can be submitted for approval.");
        }

        Status = ProjectStatus.PENDING_APPROVAL;
        SubmittedAt = now;
        SubmittedByUserId = userId;
    }

    /// <summary>Admin approval; publication is driven purely by status (13.07).</summary>
    public void Approve(Guid userId, DateTimeOffset now)
    {
        if (Status != ProjectStatus.PENDING_APPROVAL)
        {
            throw new InvalidOperationException("Only PENDING_APPROVAL projects can be approved.");
        }

        Status = ProjectStatus.APPROVED;
        ApprovedAt = now;
        ApprovedByUserId = userId;
        PublishedAt = now;
    }

    /// <summary>Admin requests changes; reviewer identity/note are recorded on the approval history row.</summary>
    public void RequestChanges()
    {
        if (Status != ProjectStatus.PENDING_APPROVAL)
        {
            throw new InvalidOperationException("Only PENDING_APPROVAL projects can receive a change request.");
        }

        Status = ProjectStatus.CHANGES_REQUESTED;
        ApprovedAt = null;
        ApprovedByUserId = null;
        PublishedAt = null;
    }

    public void Reject()
    {
        if (Status != ProjectStatus.PENDING_APPROVAL)
        {
            throw new InvalidOperationException("Only PENDING_APPROVAL projects can be rejected.");
        }

        Status = ProjectStatus.REJECTED;
        ApprovedAt = null;
        ApprovedByUserId = null;
        PublishedAt = null;
    }

    /// <summary>Suspends a published project; visibility is withdrawn with the status.</summary>
    public void Suspend()
    {
        if (Status is not (ProjectStatus.APPROVED or ProjectStatus.RECRUITING))
        {
            throw new InvalidOperationException("Only APPROVED or RECRUITING projects can be suspended.");
        }

        Status = ProjectStatus.SUSPENDED;
        PublishedAt = null;
    }

    /// <summary>Returns a suspended project to APPROVED; visibility resumes with the status.</summary>
    public void Resume()
    {
        if (Status != ProjectStatus.SUSPENDED)
        {
            throw new InvalidOperationException("Only SUSPENDED projects can be resumed.");
        }

        Status = ProjectStatus.APPROVED;
        if (ApprovedAt.HasValue)
        {
            PublishedAt = ApprovedAt;
        }
    }

    public void Complete()
    {
        if (Status == ProjectStatus.COMPLETED)
        {
            return;
        }

        if (Status != ProjectStatus.IN_PROGRESS)
        {
            throw new InvalidOperationException("Only IN_PROGRESS projects can be completed.");
        }

        Status = ProjectStatus.COMPLETED;
    }

    /// <summary>Company-side cancellation while the project has not been published yet.</summary>
    public void Cancel()
    {
        if (Status is not (ProjectStatus.DRAFT or ProjectStatus.PENDING_APPROVAL or ProjectStatus.APPROVED))
        {
            throw new InvalidOperationException("Only DRAFT, PENDING_APPROVAL or APPROVED projects can be cancelled.");
        }

        Status = ProjectStatus.CANCELLED;
        PublishedAt = null;
    }

    /// <summary>Company pulls a rejected/changes-requested/cancelled project back into a DRAFT for editing.</summary>
    public void Reopen()
    {
        if (Status is not (ProjectStatus.REJECTED or ProjectStatus.CHANGES_REQUESTED or ProjectStatus.CANCELLED))
        {
            throw new InvalidOperationException("Only REJECTED, CHANGES_REQUESTED or CANCELLED projects can be reopened.");
        }

        Status = ProjectStatus.DRAFT;
        ApprovedAt = null;
        ApprovedByUserId = null;
        PublishedAt = null;
    }

    /// <summary>Public visibility is enabled only for approved/published projects (13.07).</summary>
    public bool IsPubliclyVisible() =>
        Status is ProjectStatus.APPROVED or ProjectStatus.RECRUITING or ProjectStatus.IN_PROGRESS or ProjectStatus.COMPLETED;

    private static string? NormalizeText(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}

public sealed class ProjectSkill
{
    public Guid ProjectId { get; private set; }
    public Project Project { get; private set; } = null!;
    public Guid SkillId { get; private set; }
    public RequirementLevel RequirementLevel { get; private set; }
    public bool IsRequired { get; private set; }

    private ProjectSkill() { }

    public ProjectSkill(Guid projectId, Guid skillId, RequirementLevel requirementLevel, bool isRequired)
    {
        ProjectId = projectId;
        SkillId = skillId;
        RequirementLevel = requirementLevel;
        IsRequired = isRequired;
    }

    public void SetRequirement(RequirementLevel requirementLevel, bool isRequired)
    {
        RequirementLevel = requirementLevel;
        IsRequired = isRequired;
    }
}

public sealed class ProjectDeliverable : AuditableEntity
{
    public Guid ProjectId { get; private set; }
    public Project Project { get; private set; } = null!;
    public string Name { get; private set; } = string.Empty;
    public string? Description { get; private set; }
    public int SortOrder { get; private set; }

    private ProjectDeliverable() { }

    public ProjectDeliverable(Guid projectId, string name, string? description, int sortOrder)
    {
        ProjectId = projectId;
        Name = name.Trim();
        Description = string.IsNullOrWhiteSpace(description) ? null : description.Trim();
        SortOrder = sortOrder;
    }

    public void Update(string name, string? description, int sortOrder)
    {
        Name = name.Trim();
        Description = string.IsNullOrWhiteSpace(description) ? null : description.Trim();
        SortOrder = sortOrder;
    }
}
